using Lims.Api.Data;
using Microsoft.EntityFrameworkCore;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Lims.Api.Services;

public class InvoicePdfService
{
    private readonly AppDbContext _context;

    public InvoicePdfService(AppDbContext context)
    {
        _context = context;
    }

    public async Task<byte[]> GenerateInvoicePdfAsync(int invoiceId)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var invoice = await _context.Invoices
            .Include(i => i.Client)
            .Include(i => i.Batch)
            .Include(i => i.Lines)
            .FirstOrDefaultAsync(i => i.Id == invoiceId);

        if (invoice == null)
            throw new Exception("Invoice not found");

        var pdf = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(40);
                page.Size(PageSizes.A4);

                page.Header().Column(column =>
                {
                    column.Item().Text("LIMSberry™")
                        .FontSize(26)
                        .Bold()
                        .FontColor(Colors.Blue.Darken3);

                    column.Item().Text("Laboratory Invoice")
                        .FontSize(16)
                        .FontColor(Colors.Grey.Darken2);
                });

                page.Content().PaddingVertical(30).Column(column =>
                {
                    column.Spacing(20);

                    column.Item().Row(row =>
                    {
                        row.RelativeItem().Column(left =>
                        {
                            left.Item().Text("Invoice").FontSize(22).Bold();
                            left.Item().Text($"Invoice code: {invoice.Code}");
                            left.Item().Text($"Status: {invoice.Status}");
                            left.Item().Text($"Date: {invoice.CreatedAt:yyyy-MM-dd}");
                        });

                        row.RelativeItem().Column(right =>
                        {
                            right.Item().Text("Client").FontSize(22).Bold();
                            right.Item().Text(invoice.Client.Name);
                            right.Item().Text(invoice.Client.Email);
                            right.Item().Text(invoice.Client.Domain);
                        });
                    });

                    column.Item().Background(Colors.Grey.Lighten4).Padding(15).Column(info =>
                    {
                        info.Item().Text("Batch information").Bold().FontSize(16);
                        info.Item().Text($"Batch: {invoice.Batch.Code}");
                        info.Item().Text($"Batch status: {invoice.Batch.Status}");
                        info.Item().Text($"Analyses billed: {invoice.AnalysesCount}");
                    });

                    column.Item().Text("Invoice details").Bold().FontSize(16);

                    column.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(3);
                            columns.RelativeColumn();
                        });

                        table.Header(header =>
                        {
                            header.Cell().Element(CellHeader).Text("Analysis");
                            header.Cell().Element(CellHeader).Text("Price");
                        });

                        foreach (var line in invoice.Lines)
                        {
                            table.Cell().Element(CellBody).Text(line.Description);
                            table.Cell().Element(CellBody).Text($"{line.Price} EUR");
                        }
                    });

                    column.Item()
                        .AlignRight()
                        .Background(Colors.Green.Lighten4)
                        .Padding(18)
                        .Text($"TOTAL: {invoice.TotalAmount} EUR")
                        .FontSize(22)
                        .Bold()
                        .FontColor(Colors.Green.Darken3);
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by LIMSberry - ");
                    text.Span(DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm"));
                });
            });
        });

        return pdf.GeneratePdf();
    }

    private static IContainer CellHeader(IContainer container)
    {
        return container
            .Background(Colors.Blue.Darken3)
            .Padding(8)
            .DefaultTextStyle(x => x.FontColor(Colors.White).Bold());
    }

    private static IContainer CellBody(IContainer container)
    {
        return container
            .BorderBottom(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(8);
    }
}