using Lims.Api.Data;
using Microsoft.EntityFrameworkCore;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Lims.Api.Services;

public class QuotePdfService
{
    private readonly AppDbContext _context;

    public QuotePdfService(AppDbContext context)
    {
        _context = context;
    }

    public async Task<byte[]> GenerateQuotePdfAsync(int quoteId)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var quote = await _context.Quotes
            .Include(q => q.Client)
            .FirstOrDefaultAsync(q => q.Id == quoteId);

        if (quote == null)
            throw new Exception("Quote not found");

        var pdf = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Margin(40);
                page.Size(PageSizes.A4);

                page.Header().Column(column =>
                {
                    column.Item().Text("LIMSberry™")
                        .FontSize(26)
                        .Bold()
                        .FontColor(Colors.Blue.Darken3);

                    column.Item().Text("Laboratory Quote")
                        .FontSize(16)
                        .FontColor(Colors.Grey.Darken2);
                });

                page.Content().PaddingVertical(30).Column(column =>
                {
                    column.Spacing(20);

                    column.Item().Row(row =>
                    {
                        row.RelativeItem().Column(left =>
                        {
                            left.Item().Text("Quote").FontSize(22).Bold();
                            left.Item().Text($"Quote code: {quote.Code}");
                            left.Item().Text($"Status: {quote.Status}");
                            left.Item().Text($"Date: {quote.CreatedAt:yyyy-MM-dd}");
                        });

                        row.RelativeItem().Column(right =>
                        {
                            right.Item().Text("Client").FontSize(22).Bold();
                            right.Item().Text($"Name: {quote.Client.Name}");
                            right.Item().Text($"Email: {quote.Client.Email}");
                            right.Item().Text($"Domain: {quote.Client.Domain}");
                        });
                    });

                    column.Item().Background(Colors.Grey.Lighten4).Padding(15).Column(info =>
                    {
                        info.Item().Text("Quote information").Bold().FontSize(16);
                        info.Item().Text("This document is an estimate before laboratory execution.");
                        info.Item().Text("It is not an invoice.");
                    });

                    column.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(3);
                            columns.RelativeColumn();
                        });

                        table.Header(header =>
                        {
                            header.Cell().Element(CellHeader).Text("Description");
                            header.Cell().Element(CellHeader).Text("Estimated amount");
                        });

                        table.Cell().Element(CellBody).Text("Estimated laboratory services");
                        table.Cell().Element(CellBody).Text($"{quote.TotalAmount} EUR");
                    });

                    column.Item()
                        .AlignRight()
                        .Background(Colors.Blue.Lighten4)
                        .Padding(18)
                        .Text($"ESTIMATED TOTAL: {quote.TotalAmount} EUR")
                        .FontSize(22)
                        .Bold()
                        .FontColor(Colors.Blue.Darken3);
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by LIMSberry - ");
                    text.Span(DateTime.UtcNow.ToString("yyyy-MM-dd HH:mm"));
                });
            });
        });

        return pdf.GeneratePdf();
    }

    private static IContainer CellHeader(IContainer container)
    {
        return container
            .Background(Colors.Blue.Darken3)
            .Padding(8)
            .DefaultTextStyle(x => x.FontColor(Colors.White).Bold());
    }

    private static IContainer CellBody(IContainer container)
    {
        return container
            .BorderBottom(1)
            .BorderColor(Colors.Grey.Lighten2)
            .Padding(8);
    }
}